[package]
name = "btlepasvscan-sys"
version = "0.2.0"
authors = ["Dennis Møllegaard Pedersen <dennis@moellegaard.dk>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.42.2"
cc = "1.0"
